name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
            --url https://api.github.com/repos/kadarkojr/gha-security/issues/4/labels \
            -H 'Authorization: ***' \
            -H 'Content-Type: application/json' \
            -d '{"labels": ["bug"]}' \
            --fail
      